### ISSUE TITLE
Updated, metadata query isn't working

### ISSUE THREAD

**Issue by ajtpak** [happypandax/happypandax#166]
I just updated from 0.11.2 to the latest 0.12, and metadata isn't working anymore. Whenever I click log on a gallery it reads in the top right "Server(100)
[HappypandaError|100]: An unhandled critical error has occurred: AssertionError". 

Also after updating, in the plugins menu, it looks like all the other plugins have been removed (the only options are "install, disable, remove", and clicking install on an already installed plugin reads the following "Server(208)
[PluginInstallError|208]: The plugin files have been tampered with, aborting installation for chaika-metadata:55747a41...2a6cb1761ff4"

**Comment by twiddli** [comment]
Hi, right from the release notes:
**Because the plugin installation status has been reset, please disable the plugins prior to installing, or it'll result in an error (which is fixable by disabling, then enabling).**

> metadata isn't working anymore.

I can't do anything about this from your description alone. At least send me your logs.
Please follow the issue template next time.

**Comment by twiddli** [comment]
this error got fixed in `v0.12.2`
